apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lldap
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/a2y-d5l/ephemeral-k8s.git
    targetRevision: main
    path: gitops/apps/lldap

  destination:
    server: https://kubernetes.default.svc
    namespace: lldap

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true