apiVersion: v1
kind: Secret
metadata:
  name: lldap-secrets
  namespace: lldap
type: Opaque
# ============================================================================
# DEV-ONLY: These are intentionally weak credentials for local use.
# DO NOT use these values in production environments.
# ============================================================================
stringData:
  LLDAP_JWT_SECRET: "dev-jwt-secret"
  LLDAP_KEY_SEED: "dev-key-seed"
  LLDAP_LDAP_USER_PASS: "adminpwd"